version: '3.9'

services:
  mysql:
    image: mysql:8.3.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD} # Set the root password only
    ports:
      - "3307:3306" # Expose MySQL on port 3306
    volumes:
      - mysql:/var/lib/mysql # Persist MySQL data
    networks:
      - app_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}" # Frontend
      - "${SERVER_PORT}:${SERVER_PORT}" # Backend
    depends_on:
      - mysql
    environment:
      # Client
      PORT: ${PORT}
      REACT_APP_SERVER_BASE_URL: ${REACT_APP_SERVER_BASE_URL}
      # Server
      CLIENT_BASE_URL: ${CLIENT_BASE_URL}
      SERVER_PORT: ${SERVER_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      SHOW_SQL: ${SHOW_SQL}
      HIBERNATE_DDL: ${HIBERNATE_DDL}
      JWT_SECRET: ${JWT_SECRET}
    env_file:
      - ./client/.env 
      - ./server/.env
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mysql: # Declaring the volume to persist data
