version: '3.9'

services:
  mysql:
    image: mysql:8.3.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD} # Set the root password only
    ports:
      - "3307:3306" # Expose MySQL on port 3306
    volumes:
      - mysql:/var/lib/mysql   # Persist MySQL data
    networks:
      - app_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3003:3003" # Frontend
      - "9000:9000" # Backend
    depends_on:
      - mysql
    environment:
      SERVER_PORT: ${SERVER_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: mysql:3306
      DATABASE_USERNAME: ${DATABASE_USERNAME}   # Use root username
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      HIBERNATE_DDL: ${HIBERNATE_DDL}
      JWT_SECRET: ${JWT_SECRET}
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mysql:  # Declaring the volume to persist data
