# support reading from .env file
spring.config.import=optional:file:../.env[.properties]

# Server configuration
server.port = ${SERVER_PORT:${PORT:8080}}
spring.jpa.hibernate.naming.physical-strategy=com.agrocare.agrocare.configuration.other.CamelCasePhysicalNamingStrategy

# Database configuration
spring.datasource.name = ${DATABASE_NAME:agrocare}
spring.datasource.url = ${DATABASE_URL:jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${DATABASE_NAME:agrocare}?createDatabaseIfNotExist=true}
spring.datasource.driver-class-name = com.mysql.cj.jdbc.Driver
spring.datasource.username = ${DATABASE_USERNAME:root}
spring.datasource.password = ${DATABASE_PASSWORD:}
spring.datasource.hikari.minimum-idle = ${DB_POOL_MIN_IDLE:1}
spring.datasource.hikari.maximum-pool-size = ${DB_POOL_MAX_SIZE:3}
spring.datasource.hikari.auto-commit = ${DB_POOL_AUTO_COMMIT:true}


# Hibernate properties
spring.jpa.show-sql = ${SHOW_SQL:false}
spring.jpa.properties.hibernate.use_sql_comments = true
spring.jpa.properties.hibernate.format_sql = true
spring.jpa.properties.hibernate.boot.allow_jdbc_metadata_access = true
spring.jpa.hibernate.ddl-auto = ${HIBERNATE_DDL:update}
spring.jpa.open-in-view = true
