export const countryList = [
  { icon: '🇦🇫', value: 'HK', label: 'Afghanistan' },
  { icon: '🇦🇱', value: 'HK', label: 'Albania' },
  { icon: '🇩🇿', value: 'HK', label: 'Algeria' },
  { icon: '🇦🇩', value: 'HK', label: 'Andorra' },
  { icon: '🇦🇴', value: 'HK', label: 'Angola' },
  { icon: '🇦🇮', value: 'HK', label: 'Anguilla' },
  { icon: '🇦🇷', value: 'HK', label: 'Argentina' },
  { icon: '🇦🇲', value: 'HK', label: 'Armenia' },
  { icon: '🇦🇼', value: 'HK', label: 'Aruba' },
  { icon: '🇦🇺', value: 'HK', label: 'Australia' },
  { icon: '🇦🇹', value: 'HK', label: 'Austria' },
  { icon: '🇦🇿', value: 'HK', label: 'Azerbaijan' },
  { icon: '🇧🇸', value: 'HK', label: 'Bahamas' },
  { icon: '🇧🇭', value: 'HK', label: 'Bahrain' },
  { icon: '🇧🇩', value: 'HK', label: 'Bangladesh' },
  { icon: '🇧🇧', value: 'HK', label: 'Barbados' },
  { icon: '🇧🇾', value: 'HK', label: 'Belarus' },
  { icon: '🇧🇪', value: 'HK', label: 'Belgium' },
  { icon: '🇧🇿', value: 'HK', label: 'Belize' },
  { icon: '🇧🇯', value: 'HK', label: 'Benin' },
  { icon: '🇧🇲', value: 'HK', label: 'Bermuda' },
  { icon: '🇧🇹', value: 'HK', label: 'Bhutan' },
  { icon: '🇧🇴', value: 'HK', label: 'Bolivia' },
  { icon: '🇧🇦', value: 'HK', label: 'Bosnia and Herzegovina' },
  { icon: '🇧🇼', value: 'HK', label: 'Botswana' },
  { icon: '🇧🇷', value: 'HK', label: 'Brazil' },
  { icon: '🇧🇳', value: 'HK', label: 'Brunei Darussalam' },
  { icon: '🇧🇬', value: 'HK', label: 'Bulgaria' },
  { icon: '🇧🇫', value: 'HK', label: 'Burkina Faso' },
  { icon: '🇧🇮', value: 'HK', label: 'Burundi' },
  { icon: '🇨🇻', value: 'HK', label: 'Cabo Verde' },
  { icon: '🇰🇭', value: 'HK', label: 'Cambodia' },
  { icon: '🇨🇲', value: 'HK', label: 'Cameroon' },
  { icon: '🇨🇦', value: 'HK', label: 'Canada' },
  { icon: '🇨🇫', value: 'HK', label: 'Central African Republic' },
  { icon: '🇹🇩', value: 'HK', label: 'Chad' },
  { icon: '🇨🇱', value: 'HK', label: 'Chile' },
  { icon: '🇨🇳', value: 'HK', label: 'China' },
  { icon: '🇨🇴', value: 'HK', label: 'Colombia' },
  { icon: '🇰🇲', value: 'HK', label: 'Comoros' },
  { icon: '🇨🇩', value: 'HK', label: 'Congo' },
  { icon: '🇨🇬', value: 'HK', label: 'Congo' },
  { icon: '🇨🇷', value: 'HK', label: 'Costa Rica' },
  { icon: '🇭🇷', value: 'HK', label: 'Croatia' },
  { icon: '🇨🇺', value: 'HK', label: 'Cuba' },
  { icon: '🇨🇾', value: 'HK', label: 'Cyprus' },
  { icon: '🇨🇿', value: 'HK', label: 'Czechia' },
  { icon: '🇨🇮', value: 'HK', label: 'Cote d Ivoire' },
  { icon: '🇩🇰', value: 'HK', label: 'Denmark' },
  { icon: '🇩🇯', value: 'HK', label: 'Djibouti' },
  { icon: '🇩🇲', value: 'HK', label: 'Dominica' },
  { icon: '🇩🇴', value: 'HK', label: 'Dominican Republic' },
  { icon: '🇪🇨', value: 'HK', label: 'Ecuador' },
  { icon: '🇪🇬', value: 'HK', label: 'Egypt' },
  { icon: '🇸🇻', value: 'HK', label: 'El Salvador' },
  { icon: '🇪🇷', value: 'HK', label: 'Eritrea' },
  { icon: '🇪🇪', value: 'HK', label: 'Estonia' },
  { icon: '🇸🇿', value: 'HK', label: 'Eswatini' },
  { icon: '🇪🇹', value: 'HK', label: 'Ethiopia' },
  { icon: '🇫🇯', value: 'HK', label: 'Fiji' },
  { icon: '🇫🇮', value: 'HK', label: 'Finland' },
  { icon: '🇫🇷', value: 'HK', label: 'France' },
  { icon: '🇬🇦', value: 'HK', label: 'Gabon' },
  { icon: '🇬🇲', value: 'HK', label: 'Gambia' },
  { icon: '🇬🇪', value: 'HK', label: 'Georgia' },
  { icon: '🇩🇪', value: 'HK', label: 'Germany' },
  { icon: '🇬🇭', value: 'HK', label: 'Ghana' },
  { icon: '🇬🇮', value: 'HK', label: 'Gibraltar' },
  { icon: '🇬🇷', value: 'HK', label: 'Greece' },
  { icon: '🇬🇱', value: 'HK', label: 'Greenland' },
  { icon: '🇬🇵', value: 'HK', label: 'Guadeloupe' },
  { icon: '🇬🇺', value: 'HK', label: 'Guam' },
  { icon: '🇬🇹', value: 'HK', label: 'Guatemala' },
  { icon: '🇬🇬', value: 'HK', label: 'Guernsey' },
  { icon: '🇬🇳', value: 'HK', label: 'Guinea' },
  { icon: '🇬🇼', value: 'HK', label: 'Guinea-Bissau' },
  { icon: '🇬🇾', value: 'HK', label: 'Guyana' },
  { icon: '🇭🇹', value: 'HK', label: 'Haiti' },
  { icon: '🇭🇳', value: 'HK', label: 'Honduras' },
  { icon: '🇭🇰', value: 'HK', label: 'Hong Kong' },
  { icon: '🇭🇺', value: 'HK', label: 'Hungary' },
  { icon: '🇮🇸', value: 'HK', label: 'Iceland' },
  { icon: '🇮🇳', value: 'IN', label: 'India' },
  { icon: '🇮🇩', value: 'ID', label: 'Indonesia' },
  { icon: '🇮🇷', value: 'IR', label: 'Iran' },
  { icon: '🇮🇶', value: 'IQ', label: 'Iraq' },
  { icon: '🇮🇪', value: 'IE', label: 'Ireland' },
  { icon: '🇮🇱', value: 'IL', label: 'Israel' },
  { icon: '🇮🇹', value: 'IT', label: 'Italy' },
  { icon: '🇯🇲', value: 'JM', label: 'Jamaica' },
  { icon: '🇯🇵', value: 'JP', label: 'Japan' },
  { icon: '🇯🇴', value: 'JO', label: 'Jordan' },
  { icon: '🇰🇿', value: 'KZ', label: 'Kazakhstan' },
  { icon: '🇰🇪', value: 'KE', label: 'Kenya' },
  { icon: '🇰🇵', value: 'KP', label: 'Korea' },
  { icon: '🇰🇷', value: 'KR', label: 'Korea' },
  { icon: '🇰🇼', value: 'KW', label: 'Kuwait' },
  { icon: '🇰🇬', value: 'KG', label: 'Kyrgyzstan' },
  { icon: '🇱🇻', value: 'LV', label: 'Latvia' },
  { icon: '🇱🇧', value: 'LB', label: 'Lebanon' },
  { icon: '🇱🇸', value: 'LS', label: 'Lesotho' },
  { icon: '🇱🇷', value: 'LR', label: 'Liberia' },
  { icon: '🇱🇾', value: 'LY', label: 'Libya' },
  { icon: '🇱🇮', value: 'LI', label: 'Liechtenstein' },
  { icon: '🇱🇹', value: 'LT', label: 'Lithuania' },
  { icon: '🇱🇺', value: 'LU', label: 'Luxembourg' },
  { icon: '🇲🇬', value: 'MG', label: 'Madagascar' },
  { icon: '🇲🇼', value: 'MW', label: 'Malawi' },
  { icon: '🇲🇾', value: 'MY', label: 'Malaysia' },
  { icon: '🇲🇻', value: 'MV', label: 'Maldives' },
  { icon: '🇲🇱', value: 'ML', label: 'Mali' },
  { icon: '🇲🇹', value: 'MT', label: 'Malta' },
  { icon: '🇲🇶', value: 'MQ', label: 'Martinique' },
  { icon: '🇲🇷', value: 'MR', label: 'Mauritania' },
  { icon: '🇲🇺', value: 'MU', label: 'Mauritius' },
  { icon: '🇲🇽', value: 'MX', label: 'Mexico' },
  { icon: '🇲🇩', value: 'MD', label: 'Moldova' },
  { icon: '🇲🇨', value: 'MC', label: 'Monaco' },
  { icon: '🇲🇳', value: 'MN', label: 'Mongolia' },
  { icon: '🇲🇪', value: 'ME', label: 'Montenegro' },
  { icon: '🇲🇸', value: 'MS', label: 'Montserrat' },
  { icon: '🇲🇦', value: 'MA', label: 'Morocco' },
  { icon: '🇲🇿', value: 'MZ', label: 'Mozambique' },
  { icon: '🇲🇲', value: 'MM', label: 'Myanmar' },
  { icon: '🇳🇦', value: 'NA', label: 'Namibia' },
  { icon: '🇳🇵', value: 'NP', label: 'Nepal' },
  { icon: '🇳🇱', value: 'NL', label: 'Netherlands' },
  { icon: '🇳🇨', value: 'NC', label: 'New Caledonia' },
  { icon: '🇳🇿', value: 'NZ', label: 'New Zealand' },
  { icon: '🇳🇮', value: 'NI', label: 'Nicaragua' },
  { icon: '🇳🇪', value: 'NE', label: 'Niger' },
  { icon: '🇳🇬', value: 'NG', label: 'Nigeria' },
  { icon: '🇳🇴', value: 'NO', label: 'Norway' },
  { icon: '🇴🇲', value: 'OM', label: 'Oman' },
  { icon: '🇵🇰', value: 'PK', label: 'Pakistan' },
  { icon: '🇵🇸', value: 'PS', label: 'Palestine' },
  { icon: '🇵🇦', value: 'PA', label: 'Panama' },
  { icon: '🇵🇬', value: 'PG', label: 'Papua New Guinea' },
  { icon: '🇵🇾', value: 'PY', label: 'Paraguay' },
  { icon: '🇵🇪', value: 'PE', label: 'Peru' },
  { icon: '🇵🇭', value: 'PH', label: 'Philippines' },
  { icon: '🇵🇱', value: 'PL', label: 'Poland' },
  { icon: '🇵🇹', value: 'PT', label: 'Portugal' },
  { icon: '🇵🇷', value: 'PR', label: 'Puerto Rico' },
  { icon: '🇶🇦', value: 'QA', label: 'Qatar' },
  { icon: '🇲🇰', value: 'MK', label: 'Macedonia' },
  { icon: '🇷🇴', value: 'RO', label: 'Romania' },
  { icon: '🇷🇺', value: 'RU', label: 'Russia' },
  { icon: '🇷🇼', value: 'RW', label: 'Rwanda' },
  { icon: '🇷🇪', value: 'RE', label: 'Réunion' },
  { icon: '🇸🇦', value: 'SA', label: 'Saudi Arabia' },
  { icon: '🇸🇳', value: 'SN', label: 'Senegal' },
  { icon: '🇷🇸', value: 'RS', label: 'Serbia' },
  { icon: '🇸🇬', value: 'SG', label: 'Singapore' },
  { icon: '🇸🇰', value: 'SK', label: 'Slovakia' },
  { icon: '🇸🇮', value: 'SI', label: 'Slovenia' },
  { icon: '🇸🇴', value: 'SO', label: 'Somalia' },
  { icon: '🇿🇦', value: 'ZA', label: 'South Africa' },
  { icon: '🇸🇸', value: 'SS', label: 'South Sudan' },
  { icon: '🇪🇸', value: 'ES', label: 'Spain' },
  { icon: '🇱🇰', value: 'LK', label: 'Sri Lanka' },
  { icon: '🇸🇩', value: 'SD', label: 'Sudan' },
  { icon: '🇸🇷', value: 'SR', label: 'Suriname' },
  { icon: '🇸🇪', value: 'SE', label: 'Sweden' },
  { icon: '🇨🇭', value: 'CH', label: 'Switzerland' },
  { icon: '🇸🇾', value: 'SY', label: 'Syria' },
  { icon: '🇹🇼', value: 'TW', label: 'Taiwan' },
  { icon: '🇹🇯', value: 'TJ', label: 'Tajikistan' },
  { icon: '🇹🇿', value: 'TZ', label: 'Tanzania' },
  { icon: '🇹🇭', value: 'TH', label: 'Thailand' },
  { icon: '🇹🇱', value: 'TL', label: 'Timor-Leste' },
  { icon: '🇹🇬', value: 'TG', label: 'Togo' },
  { icon: '🇹🇴', value: 'TO', label: 'Tonga' },
  { icon: '🇹🇳', value: 'TN', label: 'Tunisia' },
  { icon: '🇹🇷', value: 'TR', label: 'Turkey' },
  { icon: '🇹🇲', value: 'TM', label: 'Turkmenistan' },
  { icon: '🇺🇬', value: 'UG', label: 'Uganda' },
  { icon: '🇺🇦', value: 'UA', label: 'Ukraine' },
  { icon: '🇦🇪', value: 'AE', label: 'United Arab Emirates', },
  { icon: '🇬🇧', value: 'GB', label: 'United Kingdom' },
  { icon: '🇺🇸', value: 'US', label: 'United States' },
  { icon: '🇺🇾', value: 'UY', label: 'Uruguay' },
  { icon: '🇺🇿', value: 'UZ', label: 'Uzbekistan' },
  { icon: '🇻🇪', value: 'VE', label: 'Venezuela' },
  { icon: '🇻🇳', value: 'VN', label: 'Vietnam' },
  { icon: '🇾🇪', value: 'YE', label: 'Yemen' },
  { icon: '🇿🇲', value: 'ZM', label: 'Zambia' },
  { icon: '🇿🇼', value: 'ZW', label: 'Zimbabwe' },
];
